export const navigation = [
    {
        id: "0",
        title: "Lending Protocol",
        element_color: "green-600",
        url: "#",
        active: true,
        is_mobile: false,
    },
    {
        id: "1",
        title: "Liquid Stacking",
        element_color: "blue-600",
        url: "#",
        active: false,
        is_mobile: false,
    },
    {
        id: "2",
        title: "Ush Stacking",
        element_color: "cyan-500",
        url: "#",
        active: false,
        is_mobile: false,
    },
    {
        id: "3",
        title: "Soul Protocol",
        element_color: "gray-400",
        url: "#",
        active: false,
        is_mobile: false,
    },
    {
        id: "4",
        title: "Tag Bride",
        element_color: "red-800",
        url: "#",
        active: false,
        is_mobile: false,
    },
    {
        id: "5",
        title: "More",
        element_color: "yellow-400",
        url: "#",
        active: false,
        is_mobile: false,
    },
    {
        id: "6",
        title: "MultiversX",
        element_color: "cyan-200",
        url: "#",
        active: false,
        is_mobile: true,
    },
    {
        id: "7",
        title: "QXF9976QXF914A8",
        element_color: "purple-500",
        url: "#",
        active: false,
        is_mobile: true,
    },
    {
        id: "8",
        title: "Settings",
        element_color: "",
        url: "#",
        active: false,
        is_mobile: true,
    },
];

export const sidebarData = {
    net_apy: "23,320",
    supply_balance: "100,000.0617916",
    borrow_balance: "240,050.0617916",
    borrow_limit: "800",
    borrow_limit_used: "28",
    htm_booster: "5,050.0617916",
};
