export const navigation = [
    {
        id: "0",
        title: "Lending Protocol",
        element_color: "green-600",
        url: "#",
        active: true,
        is_mobile: false,
    },
    {
        id: "1",
        title: "Liquid Stacking",
        element_color: "blue-600",
        url: "#",
        active: false,
        is_mobile: false,
    },
    {
        id: "2",
        title: "Ush Stacking",
        element_color: "cyan-500",
        url: "#",
        active: false,
        is_mobile: false,
    },
    {
        id: "3",
        title: "Soul Protocol",
        element_color: "gray-400",
        url: "#",
        active: false,
        is_mobile: false,
    },
    {
        id: "4",
        title: "Tag Bride",
        element_color: "red-800",
        url: "#",
        active: false,
        is_mobile: false,
    },
    {
        id: "5",
        title: "More",
        element_color: "yellow-400",
        url: "#",
        active: false,
        is_mobile: false,
    },
    {
        id: "6",
        title: "MultiversX",
        element_color: "cyan-200",
        url: "#",
        active: false,
        is_mobile: true,
    },
    {
        id: "7",
        title: "QXF9976QXF914A8",
        element_color: "purple-500",
        url: "#",
        active: false,
        is_mobile: true,
    },
    {
        id: "8",
        title: "Settings",
        element_color: "",
        url: "#",
        active: false,
        is_mobile: true,
    },
];

export const sidebarData = {
    net_apy: "23,320",
    supply_balance: "100,000.0617916",
    borrow_balance: "240,050.0617916",
    borrow_limit: "800",
    borrow_limit_used: "28",
    htm_booster: "5,050.0617916",
};

export const assetData = [
    {
        id: 1,
        name: "Multiversx",
        currency: "egld",
        apy: "5.552",
        wallet: "245",
        collateral: "0.00",
    },
    {
        id: 2,
        name: "Bitcoin",
        currency: "btc",
        apy: "2.345",
        wallet: "189",
        collateral: "0.50",
    },
    {
        id: 3,
        name: "Ethereum",
        currency: "eth",
        apy: "4.321",
        wallet: "367",
        collateral: "1.20",
    },
    {
        id: 4,
        name: "Cardano",
        currency: "ada",
        apy: "6.789",
        wallet: "412",
        collateral: "2.00",
    },
    {
        id: 5,
        name: "Polkadot",
        currency: "dot",
        apy: "7.001",
        wallet: "523",
        collateral: "3.00",
    },
    {
        id: 6,
        name: "Solana",
        currency: "sol",
        apy: "5.999",
        wallet: "642",
        collateral: "0.75",
    },
    {
        id: 7,
        name: "Avalanche",
        currency: "avax",
        apy: "3.214",
        wallet: "278",
        collateral: "1.50",
    },
    {
        id: 8,
        name: "Chainlink",
        currency: "link",
        apy: "4.912",
        wallet: "355",
        collateral: "0.30",
    },
    {
        id: 9,
        name: "Litecoin",
        currency: "ltc",
        apy: "2.885",
        wallet: "486",
        collateral: "1.75",
    },
    {
        id: 10,
        name: "Uniswap",
        currency: "uni",
        apy: "5.432",
        wallet: "194",
        collateral: "0.00",
    },
    {
        id: 11,
        name: "Binance Coin",
        currency: "bnb",
        apy: "4.567",
        wallet: "533",
        collateral: "1.10",
    },
    {
        id: 12,
        name: "Tezos",
        currency: "xtz",
        apy: "6.013",
        wallet: "657",
        collateral: "0.65",
    },
    {
        id: 13,
        name: "Cosmos",
        currency: "atom",
        apy: "8.200",
        wallet: "323",
        collateral: "2.00",
    },
    {
        id: 14,
        name: "Stellar",
        currency: "xlm",
        apy: "3.678",
        wallet: "276",
        collateral: "1.25",
    },
    {
        id: 15,
        name: "Algorand",
        currency: "algo",
        apy: "7.345",
        wallet: "493",
        collateral: "0.95",
    },
    {
        id: 16,
        name: "Aave",
        currency: "aave",
        apy: "6.123",
        wallet: "371",
        collateral: "0.80",
    },
    {
        id: 17,
        name: "Fantom",
        currency: "ftm",
        apy: "5.789",
        wallet: "419",
        collateral: "1.40",
    },
];
